CREATE USER 'olive'@'localhost' IDENTIFIED VIA mysql_native_password USING '***';
REVOKE ALL PRIVILEGES ON *.* FROM 'olive'@'localhost';
GRANT ALL PRIVILEGES ON *.* TO 'olive'@'localhost' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
